apiVersion: v1
kind: PersistentVolume
metadata:
  name: concourse-web-pv
spec:
  storageClassName: concourse-web-storage
  capacity:
    storage: 1G
  accessModes:
  - ReadWriteOnce
  PersistentVolumeReclaimPolicy: Retain
  local:
    path: /var/db/kubernetes/kubercourse/concourse-web-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
