apiVersion: v1
kind: PersistentVolume
metadata:
  name: concourse-worker-pv
spec:
  storageClassName: concourse-worker-storage
  capacity: 
    storage: 1G
  accessModes:
  - ReadWriteOnce
  PersistentVolumeReclaimPolicy: Retain
  local:
    path: </some/path/to/concourse/keys/worker>
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - <some_node>
