apiVersion: v1
kind: PersistentVolume
metadata:
  name: concourse-worker-pv
spec:
  storageClassName: concourse-worker-storage
  capacity: 
    storage: 1G
  accessModes:
  - ReadWriteOnce
  PersistentVolumeReclaimPolicy: Retain
  local:
    path: /var/db/kubernetes/kubercourse/concourse-worker-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
